FROM kong/kong-gateway:3.11.0.0

USER root

# Install build dependencies for plugin compilation
RUN apt-get update \
 && apt-get install -y git build-essential curl libssl-dev unzip pkg-config luarocks \
 # Install dependencies for the plugin
 && luarocks install lua-resty-openidc 1.6.0-1 \
 && luarocks install kong-oidc 1.0.1 \
 && rm -rf /var/lib/apt/lists/*

USER kong
