server:
  port: 9000

spring:
  application:
    name: user-service

  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: ${AUTH0_REDIRECT_URI}  # or "{baseUrl}/login/oauth2/code/{registrationId}" if dynamic
            client-name: Auth0
            authorization-grant-type: authorization_code
        provider:
          auth0:
            issuer-uri: ${AUTH0_ISSUER_URI}

      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}

custom:
  auth0:
    audience: ${AUTH0_AUDIENCE}
    logout-url: ${AUTH0_LOGOUT_REDIRECT_URL}
    frontend-redirect-url: ${FRONTEND_REDIRECT_URL}

logging:
  level:
    org:
      springframework:
        security: trace
