server:
  port: 9000
spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-p0goqmyozbhmcoys.us.auth0.com/
          audience: https://dev-p0goqmyozbhmcoys.us.auth0.com/api/v2/

# Add these properties that match your SecurityConfig class
auth0:
  audience: https://dev-p0goqmyozbhmcoys.us.auth0.com/api/v2/
  issuer: https://dev-p0goqmyozbhmcoys.us.auth0.com/

logging:
  level:
    org:
      springframework:
        security: trace